### ISSUE TITLE
Clone and ship me one ? 

### ISSUE THREAD

**Issue by omarali-me** [andreabenini/FatBottomedBoard#1]
Hey dude, beautiful work.

And I would love nothing more than exactly the same. 
Would you be willing to make a replica ?

**Comment by andreabenini** [comment]
Thanks Omar.
I froze my reply for a while to understand whatever it takes to create a new one. I've documented each single step of the production process, it was created to be a cheap project with scavenged parts and I was able to achieve it mostly because big savings were related to switches, pcb and keyboard frame. Brand new hardware parts for the project costed me ~30/40$ so I'm quite happy about that.
I had at my disposal two broken AT/XT keyboards so I collected switches from there (~50/60$ switches value), some 2mm stainless steel and plenty of time. Manual work is what made the real difference, from drilling steel to handwiring everything (two times: keyboard matrix and backlight), lockdown helped in this case...
Firmware programming is almost complete and electronics part is simple.

I've had requests (like yours) after the HackADay article effect so I'm considering it, I'm now evaluating a small batch but CNC steel machining price is insane and spending 2/3 months to manually work on each single piece is not a viable option.
I'll try to experiment few things like CNC & PCB milling to see if I can work on a small batch (collaborations are warmly encouraged) and I'll surely publish info here where available.

Comments Welcomed :)
